### ISSUE TITLE
[BUG] Bad handler in spam module

### ISSUE THREAD

**Issue by MattiaFailla** [Kavuti/python-italy-telegram-bot#16]
Il modulo spam, che veniva caricato dal bot, ad oggi non permette il corretto funzionamento dei dispatcher degli altri moduli.

Suggerisco di disabilitarlo e spostare lo sviluppo su branch differente.

**Comment by iflare3g** [comment]
Il problema è che anche mettendolo nei NO_LOAD, l'help , per esempio, si rompe nel gruppo e non in privato.
Ho provato a mettere qualche log di debug e ho notato che non arriva neanche prima del blocco if in cui controlliamo il tipo di chat , quindi sembra che non riesce proprio a chiamare get_help() e non riesco a capirne il motivo 
Con bisect in realtà sono riuscito a trovare un punto in cui, anche in dev con docker, l'help funziona di nuovo nel gruppo

**Comment by iflare3g** [comment]
Easy fix : aggiungere log_channel ai NO_LOAD

**Comment by iflare3g** [comment]
Chiudo la issue, il fix comunque va bene disattivando il modulo spam al momento, così capiamo per bene cosa ci vogliamo fare e ci lavoriamo.
