### ISSUE TITLE
[improvement] Modifiche al log channel

### ISSUE THREAD

**Issue by Kavuti** [Kavuti/python-italy-telegram-bot#19]
Ciao,
stavo pensando ad eventuali modifiche possibili per il modulo log channel:
- Creazione di un canale separato per distinguere i provvedimenti dalle risorse
- Meccanismo di marcatura delle risorse tramite hashtag per garantirne una descrizione minimale (non dovendo così "interpretare" la url per capire di cosa si tratta) e renderle tracciabili per argomento all'interno del canale preposto

Fatemi sapere se le considerate modifiche valide.

**Comment by iflare3g** [comment]
Per me va benissimo, unico dubbio sugli hashtag è che spetterà poi a chi condivide il link di aggiungerli al suo messaggio ?

**Comment by Kavuti** [comment]
Per il momento si, visto che comunque non sempre può saperlo qualcun altro che cosa sta condividendo una certa persona. Magari poi potremo anche riservare agli admin il diritto di aggiungere hashtag ad una certa risorsa e far sì che il bot modifichi il messaggio precedentemente inviato, ma partirei prima col lasciare il compito all'utente.

**Comment by iflare3g** [comment]
Perfetto, ho anche una mezza idea a riguardo, ma preferisco testarla domani prima di dire una cazzata e poi ve la propongo.

**Comment by MattiaFailla** [comment]
Per la tracciabilità degli url perchè non progettiamo un hastag che si basi solo sul dominio? 
es:
www.github.com/bla/bla -> #github

**Comment by iflare3g** [comment]
> Per la tracciabilità degli url perchè non progettiamo un hastag che si basi solo sul dominio?
> es:
> [www.github.com/bla/bla](http://www.github.com/bla/bla) -> #github

La mia idea era più o meno quella, in realtà ero in incuriosito dalle librerie di keywords extraction per estrarre dai link che gli utenti condividevano in automatico un set di hashtag, però forse un link ha poche info per essere un input plausibile per quegli algoritmi
Ditemi voi se magari avete più esperienza a riguardo

**Comment by Kavuti** [comment]
Non ho esperienza a riguardo, però credo sia fattibile. Unica cosa che non mi è chiara è se questa cosa andrebbe a creare un hashtag che viene usato ignorando gli altri o se si tratta semplicemente di un hashtag complementare a quelli da far inserire all'utente.

**Comment by MattiaFailla** [comment]
Io pensavo a qualcosa di complementare.

**Comment by iflare3g** [comment]
> Io pensavo a qualcosa di complementare.

Idem! 
In realtà ho testato [rake](https://github.com/fabianvf/python-rake), ma penso che soltato la url sia troppo poco come input per fargli estrarre delle keywords coerenti.

**Comment by MattiaFailla** [comment]
Io invece ho trovato questa cosa interessante che fa esattamente quello che avevo descritto [qui](https://github.com/Kavuti/python-italy-telegram-bot/issues/19#issuecomment-515801758):

[https://pypi.org/project/urlextract/](https://pypi.org/project/urlextract/)

**Comment by iflare3g** [comment]
> Io invece ho trovato questa cosa interessante che fa esattamente quello che avevo descritto [qui](https://github.com/Kavuti/python-italy-telegram-bot/issues/19#issuecomment-515801758):
> 
> https://pypi.org/project/urlextract/

bella, ho solo due dubbi a riguardo
il primo è che lo status su PyPi dà che è in beta 😢 , il secondo è che se tipo da github.com/bla/ ti estrae solo github.com e fai l'hashtag #github, quest'ultimo come aiuterà nella ricerca ? cioè dovremmo comunque aggiungere degli hashtag relativi anche al topic di quella risorsa condivisa in modo da aiutare il membro del gruppo a effettuare una ricerca più mirata o sto dicendo baggianate ? 😆

**Comment by Kavuti** [comment]
Mi trovo in questo momento ad implementare la gestione degli hashtag, ma volevo condividere con voi alcune riflessioni. Ipotizzando che un utente invii due link nello stesso messaggio, attualmente questi verrebbero inviati come risorse separate. Se l'utente invia degli hashtag associati alle risorse risulta però difficile capire ogni hashtag a quale risorsa appartiene. Pensavo quindi di inserire tutti gli hashtag di un messaggio ad ogni url nel messaggio, in modo da dare una tracciabilità in ogni caso maggiore di quella che l'utente ha espresso. Che ne dite?

UPDATE:
Per l'estrazione dell'hashtag dell'url ho trovato https://pypi.org/project/tldextract/. Appena potete dategli uno sguardo, a me sembra che sia sufficiente per tirare fuori il domain e crearne un hashtag... intanto ci gioco un po'.

**Comment by iflare3g** [comment]
PR #21

**Comment by MattiaFailla** [comment]
PR approvata: https://github.com/Kavuti/python-italy-telegram-bot/commit/bd98a20ce2a7d39145c6f11e96a13a4a3a5c9552
