### ISSUE TITLE
[Refactoring] documentazione

### ISSUE THREAD

**Issue by MattiaFailla** [Kavuti/python-italy-telegram-bot#2]
In giornata modificherò il file readme con una veste più elegante e una sezione dedicata alla configurazione sia su heroku che su vps.

Volete che aggiunga qualcosa di particolare? 
Come template pensavo di riciclare la stessa utilizzata sulla repo di [Jelly](https://github.com/MattiaFailla/Jelly)

**Comment by Kavuti** [comment]
Concordo. Anche per non sembrare una copia qualunque di tgbot credo sia necessario. In ogni caso lascio qui il link del gist riguardante il template che utilizzai inizialmente su Jelly.

https://gist.github.com/PurpleBooth/109311bb0361f32d87a2

Aggiunte particolari non credo servano. Al massimo, si può scrivere di quello che abbiamo integrato/integreremo, giusto per far capire a che serve la repo.

**Comment by iflare3g** [comment]
Fantastico, io avevo aggiunto giusto la parte di docker senza toccare il resto del README visto che non ne avevamo discusso.
Quel template va benissimo a mio parere 😁

**Comment by MattiaFailla** [comment]
Pull request inviata.
