### ISSUE TITLE
FORMAT CODE WITH BLACK

### ISSUE THREAD

**Issue by iflare3g** [Kavuti/python-italy-telegram-bot#20]
Se per voi va bene, mi piacerebbe formattare il codice utlizzando [black](https://github.com/psf/black), magari configurandolo con [pre-commit](https://pre-commit.com/) così ogni commit sarà formattato seguendo PEP8.
Fatemi sapere cosa ne pensate 😄

**Comment by basic-ph** [comment]
Let's go **black**!

**Comment by Kavuti** [comment]
Per me va bene. In ogni caso io mi baso sui consigli di PyCharm per poter applicare PEP 8

**Comment by iflare3g** [comment]
> Per me va bene. In ogni caso io mi baso sui consigli di PyCharm per poter applicare PEP 8

Dovrebbe esserci anche il plugin in PyCharm per black o flake8, in ogni caso col pre-commit la formattazione la farà in automatico ( ti darà warnings in caso di problemi ) e così almeno siamo sicuri che ogni commit sarà PEPpizzato 🤣 
Poi vuoi mettere avere il badge di black alla repo 😆

**Comment by iflare3g** [comment]
Merged #23
