### ISSUE TITLE
[improvement] Aggiungere RSS per i libri di packtpub 

### ISSUE THREAD

**Issue by iflare3g** [Kavuti/python-italy-telegram-bot#22]
Visto che , da quanto scrivono nel gruppo, il bot che informava dei libri del giorno non funziona più, potremmo integrarlo lavorando sul modulo rss di tgbot.

**Comment by Kavuti** [comment]
Concordo, per me è fattibile. Unica cosa va verificato che l'RSS sia il metodo che usava il vecchio bot.

**Comment by iflare3g** [comment]
Credo di si, https://hub.packtpub.com/feed/ questa è la url per mettersi in ascolto dei feed.

**Comment by iflare3g** [comment]
Poi come vorreste implementarlo ? Il bot ufficiale ha chiuso, perchè PacktPub ha introdotto politiche anti-scraping.
Il feed RSS l'ho parsato tranquillamente, però per "ascoltare" in automatico l'aggiunta di nuovi libri dovremmo utilizzare un job in background che faccia il controllo dell'E-Tag e del suo status_code
Se è 304 non sono stati aggiunti libri, altrimenti lo status_code è 200.
Però non ho molta esperienza a riguardo, voi avete già trattato i feed RSS ?

**Comment by iflare3g** [comment]
Aggiorno anche qui il discorso RSS. 
Packtpub non è più utilizzabile per i libri, l'idea era quella di trovare un altro feed.
https://blog.feedspot.com/python_rss_feeds/
Qua c'è una lista di quelli più "famosi"
Per quanto riguarda l'implementazione, quella del modulo rss va già bene, cambierei giusto due cose per rendere più comodi i comandi di list dei canali ascoltati.
