### ISSUE TITLE
Kick automatico se l'username non è impostato

### ISSUE THREAD

**Issue by henryx** [Kavuti/python-italy-telegram-bot#26]
Al fine di permettere una migliore gestione del gruppo, sarebbe opportuno implementare un kick automatico di tutti gli account che non hanno impostato uno username. L'obiettivo è di evitare il proliferarsi di tutti gli userbot che effettuano il join al canale con l'intento di proporre spam

**Comment by MattiaFailla** [comment]
Questa feature è stata integrata nel seguente commit: 80dc0b9c4fc15951b1f8c2193d84fccd05c53430
