### ISSUE TITLE
[BUG] Fix markdown 

### ISSUE THREAD

**Issue by MattiaFailla** [Kavuti/python-italy-telegram-bot#3]
The markdown help module needs a review due to internal server error while handling the response message for the command /markdownhelp

The following error is raised:

`
Traceback (most recent call last):
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/utils/promise.py", line 57, in run
    self._result = self.pooled_function(*self.args, **self.kwargs)
  File "/home/USER/modules/misc.py", line 348, in markdown_help
    update.effective_message.reply_text(MARKDOWN_HELP, parse_mode=ParseMode.HTML)
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/message.py", line 455, in reply_text
    return self.bot.send_message(self.chat_id, *args, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/home/USER/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Can't parse entities: unclosed end tag at byte offset 247
`

We need to fix this bug to guarantee no errors while handling reply from tgbot.

**Comment by Kavuti** [comment]
Ho alcune domande da porre in merito:
- Ogni quanto si verifica?
- Si verifica sempre nello stesso modulo/file?
- Com'è composto il messaggio con cui viene generato l'errore?
- Potrebbe essere una problematica importante a tal punto da segnalare ai gestori di tgbot (sebbene considerato deprecato per far posto alla versione in Go) la presenza di un errore?

Soprattutto porrei attenzione sull'ultima domanda. Una volta che risolviamo, magari un giorno potrebbe essere utile a qualcun altro, anche integrando la nostra soluzione a tgbot originale con una pull request.

**Comment by MattiaFailla** [comment]
Rispondendo alle tue domande:
- Si verifica sporadicamente al richiamo del comando `/markdownhelp`
- Ho visto questo errore solo in questo specifico modulo ma io investigherei ulteriormente anche negli altri moduli; sospetto che il bug sia in un submodule che gestisce tutto il markdown del bot
- Il messaggio viene generato ogni volta che il suddetto comando viene inviato
- Non so se è un problema così vasto; in tal caso credo che una pull request non sia un problema.

**Comment by iflare3g** [comment]
Proverò a cercare anche io, se lo risolvo farò PR

**Comment by MattiaFailla** [comment]
Problema risolto disattivando il comando. Il problema non si presenta più.
Chiudo issue
