### ISSUE TITLE
[improvement] Effective way to limitate spam

### ISSUE THREAD

**Issue by MattiaFailla** [Kavuti/python-italy-telegram-bot#4]
Concentrerei qui la discussione tecnica per limitare i fenomeni di spam e flood.

Per quanto riguarda il flooding il modulo di tgbot sembra fare il suo lavoro; si può integrare un controllo sul numero di caratteri per evitare messaggi enormi e inutili.

**Comment by Kavuti** [comment]
Credo che per gestire al meglio la cosa si possano integrare i provvedimenti warn, mute, kick e ban al violare delle regole definite da locks. Ovvero quando un utente non-admin invia cose bloccate da locks, oltre che provvedere all'eliminazione del messaggio, si stabilisce se procedere con i provvedimenti, in base al numero di provvedimenti già presi precedentemente per quell'utente. Può essere inoltre utile ricontrollare i vari filtri usati da locks e vedere se è necessario integrarne altri, modificare quelli attuali (condizione già verificatasi e attualmente in funzione per le url) o lasciarli così come sono.

**Comment by MattiaFailla** [comment]
Potremmo integrare la stessa logica dei warn: ogni volta che viene violato un lock scatta anche un warn, una volta superati X warn si procede al kick.

**Comment by iflare3g** [comment]
Mi piace come idea, ha senso fargli un warn se viola una "legge" dettata dai locks

**Comment by Kavuti** [comment]
Penso si possa procedere così per il momento, poi si potranno anche integrare i canali di spam watch per avere le liste di account già plurisegnalati e conosciuti come spam (come dicevamo nella issue precedente inerente allo stesso argomento)

**Comment by MattiaFailla** [comment]
Va bene.

Nel caso in cui riuscissimo a trovare una lista di id già segnalati potremmo caricarli in tgbot nel modulo gban!

**Comment by iflare3g** [comment]
Per questo vorrei capire come funzionano le federation di Rose/Marie, visto che servirebbe proprio per avere accesso a quella lista

**Comment by Kavuti** [comment]
Non conosco bene l'argomento, quindi per questa cosa rimetto tutto nelle vostre mani.

**Comment by MattiaFailla** [comment]
Ciao ragazzi,
in questi giorni sto implementando il sistema di warn quando viene violato un lock. 

Ditemi se non siete d'accordo con questo sistema e provvedo a modificare il lavoro.

**Comment by iflare3g** [comment]
Per me va bene, anzi se ti serve una mano fammi sapere 😄

**Comment by Kavuti** [comment]
Ma quindi come siamo rimasti su questo punto? Mi fate un recap?

**Comment by MattiaFailla** [comment]
Sul gruppo non erano tutti d'accordo e quindi non ho pushato nulla.

**Comment by iflare3g** [comment]
Qua ritorna il discorso del CAS che hai già implementato @MattiaFailla ( se non ricordo male ) , quello dovrebbe già limitare il problema spam.
Poi se è uno spammer che non è presente nei db di CAS, c'è sempre il `/ban`

**Comment by MattiaFailla** [comment]
Si, ho implementato il sistema CAS e pushato su master! In teoria siamo al sicuro dalla maggor parte di spammers.. ovviamente qualcuno non verrà bloccato/riconosciuto e come diceva @iflare3g ci torna utile il comando **/ban**

Electus è già operativo con questa feature.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by iflare3g** [comment]
Al massimo dovremmo salvare i messaggi di quelli che banniamo con `/ban` e confrontarli con il messaggio che viene inviato dopo il join al gruppo di un nuovo utente ( ma dovrebbero comunque superare il discorso del `/CocDone` ) quindi penso che già allo stato attuale dovremmo avere le spalle coperte.

**Comment by MattiaFailla** [comment]
Si esatto, in teoria siamo abbastanza al sicuro. Credo che coc + CAS siano già abbastanza per limitare bot del genere.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by MattiaFailla** [comment]
Chiudo per inattività 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
