### ISSUE TITLE
[Improvement] Broadcast degli eventi tramite canale apposito

### ISSUE THREAD

**Issue by Kavuti** [Kavuti/python-italy-telegram-bot#5]
Sull'altra repository si era ipotizzata la creazione di un canale in cui il bot avrebbe potuto inoltrare i messaggi riguardanti eventi particolari come provvedimenti (warn, mute, kick, ban) o altri messaggi che potrebbero essere utili, magari anche tutti. Ciò garantirebbe una buona tracciabilità dei messaggi del bot, che non si perderebbero nel volume di messaggi del gruppo (che seppur ancora piccolo ha già una partecipazione sufficiente a far perdere i messaggi del bot). Che ne pensate? Secondo voi è realmente utile? Se sì, quanti e quali messaggi si potrebbe pensare di replicare sul canale dedicato?

**Comment by iflare3g** [comment]
Non so se I warn/kick ecc ecc sarebbero utili, cioè dovremmo poter tramite qualcosa del tipo /user user_id agli eventi relativi a quell'utente se nel caso servisse, se non erro tgbot dovrebbe già aver qualcosa di questo tipo
Però magari sarebbe interessante raccogliere i messaggi relativi ai link verso le risorse che vengono condivisi nel gruppo , un po' come è il canale @pythonres

**Comment by Kavuti** [comment]
Mi sembra interessante una raccolta di risorse. Si può integrare facilmente.

UPDATE:
Il meccanismo è implementato e attualmente pushato sulla repository.
